export const initialValueProductCreate: IProductCreate = {
  title: "",
  type: "",
  content: "",
  address: "",
  bathroom: "",
  bedroom: "",
  square: "",
  status: "",
  price: 0,
  sequence: 0,
  quantity: 0,
  start_price: 0,
  cluster_id: "",
};

export const getInitialValuesUpdateProduct = (productData?: Partial<IProductUpdate>): IProductUpdate => ({
  id: productData?.id || "",
  title: productData?.title || "",
  type: productData?.type || "",
  content: productData?.content || "",
  address: productData?.address || "",
  bathroom: productData?.bathroom || "",
  bedroom: productData?.bedroom || "",
  square: productData?.square || "",
  status: productData?.status || "",
  price: productData?.price || 0,
  sequence: productData?.sequence || 0,
  quantity: productData?.quantity || 0,
  start_price: productData?.start_price || 0,
  cluster_id: productData?.cluster_id ?? null,
});
